# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-simply_documents}
  s.version = "1.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = %q{2010-11-24}
  s.description = %q{longer description of your gem}
  s.email = %q{github@jake.otherinbox.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/documents_controller.rb",
    "app/models/document.rb",
    "app/views/documents/_document.html.erb",
    "app/views/documents/_form.html.erb",
    "app/views/documents/edit.html.erb",
    "app/views/documents/index.html.erb",
    "app/views/documents/new.html.erb",
    "app/views/documents/preview.html.erb",
    "config/document.yml",
    "config/routes.rb",
    "generators/simply_documents/USAGE",
    "generators/simply_documents/simply_documents_generator.rb",
    "generators/simply_documents/templates/autotest_simply_documents.rb",
    "generators/simply_documents/templates/functional/documents_controller_test.rb",
    "generators/simply_documents/templates/javascripts/documents.js",
    "generators/simply_documents/templates/migrations/add_attachments_document_to_document.rb",
    "generators/simply_documents/templates/migrations/create_documents.rb",
    "generators/simply_documents/templates/migrations/polymorphicize_document_owner.rb",
    "generators/simply_documents/templates/simply_documents.rake",
    "generators/simply_documents/templates/stylesheets/documents.css",
    "generators/simply_documents/templates/unit/document_test.rb",
    "lib/simply_documents.rb",
    "lib/simply_documents/autotest.rb",
    "lib/simply_documents/factories.rb",
    "lib/simply_documents/file_utils_extension.rb",
    "lib/simply_documents/owner.rb",
    "lib/simply_documents/tasks.rb",
    "lib/simply_documents/test_tasks.rb",
    "lib/tasks/application.rake",
    "lib/tasks/calnet_authenticated.rake",
    "lib/tasks/database.rake",
    "lib/tasks/documentation.rake",
    "lib/tasks/rcov.rake",
    "lib/tasks/simply_authorized.rake",
    "lib/tasks/simply_helpful.rake",
    "lib/tasks/ucb_ccls_engine_tasks.rake"
  ]
  s.homepage = %q{http://github.com/jakewendt/simply_documents}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/app/controllers/application_controller.rb",
    "test/app/controllers/home_controller.rb",
    "test/app/models/user.rb",
    "test/assets/edit_save_wireframe.pdf",
    "test/config/routes.rb",
    "test/functional/documents/documents_controller_test.rb",
    "test/unit/documents/document_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 2"])
      s.add_runtime_dependency(%q<jakewendt-simply_helpful>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-simply_authorized>, [">= 0"])
      s.add_runtime_dependency(%q<chronic>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
      s.add_runtime_dependency(%q<ssl_requirement>, [">= 0"])
      s.add_runtime_dependency(%q<ryanb-acts-as-list>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 2"])
      s.add_dependency(%q<jakewendt-simply_helpful>, [">= 0"])
      s.add_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
      s.add_dependency(%q<jakewendt-simply_authorized>, [">= 0"])
      s.add_dependency(%q<chronic>, [">= 0"])
      s.add_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_dependency(%q<aws-s3>, [">= 0"])
      s.add_dependency(%q<ssl_requirement>, [">= 0"])
      s.add_dependency(%q<ryanb-acts-as-list>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 2"])
    s.add_dependency(%q<jakewendt-simply_helpful>, [">= 0"])
    s.add_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
    s.add_dependency(%q<jakewendt-simply_authorized>, [">= 0"])
    s.add_dependency(%q<chronic>, [">= 0"])
    s.add_dependency(%q<ruby-hmac>, [">= 0"])
    s.add_dependency(%q<aws-s3>, [">= 0"])
    s.add_dependency(%q<ssl_requirement>, [">= 0"])
    s.add_dependency(%q<ryanb-acts-as-list>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
  end
end

